# Getting Sample Dataset :D

In [16]:
import pandas as pd
import json
import shutil
from pathlib import Path

In [3]:
BASE_DIR = Path("S:/Zulassungskarten_Data/R_9346-I_Zulassungskarten")

metadata = []

for json_path in BASE_DIR.rglob("*.json"):

    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)

            data["_source_folder"] = json_path.parent.name
            data["_file_name"] = json_path.name

            metadata.append(data)

    except (json.JSONDecodeError, IOError) as e:
        print(f"Fehler beim Lesen von {json_path}: {e}")

df = pd.DataFrame(metadata)
df

,Titel_und_Signatur,Bemerkung,Prüfnummer,Prüfdatum,Antragsteller,Produktion,Land,Filmart,Stumm-/Tonfilm,Länge (in Meter),Entscheidung,Unterlagenart,Benutzungsort,_source_folder,_file_name,Vorführungsbeschränkung,Ort des Prüfdatums
0,R 9346-I/1\nDie Wölfin.\n1920 - 1945,nach Kürzung 1480 m,2,24.6.1920,"Solar-Film-Ges., Berlin","Solar-Film-Ges., Berlin",Deutschland,Puppenfilm,Stummfilm,1485,Jugendverbot,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_1,R 9346-I_1.json,NaN,NaN
1,R 9346-I/10\nDie tote Stunde\n1920 - 1945,NaN,52,5.7.1920,"Ungo-Film-Ges. Unger u. Gottschalk, Berlin","Ungo-Film-Ges. Unger u. Gottschalk, Berlin",Deutschland,Spielfilm,Stummfilm,1715,Jugendverbot,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_10,R 9346-I_10.json,NaN,NaN
2,R 9346-I/100\nNur ein Flimmerstern\n1920,NaN,527,2.10.1920,"Ebert-Film GmbH, Berlin","Ebert-Film GmbH, Berlin",Deutschland,Spielfilm,Stummfilm,1135,Jugendverbot,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_100,R 9346-I_100.json,NaN,NaN
3,R 9346-I/1000\nSein Pelzmäuschen.\n1920 - 1945,"nach Kürzung 695,30 m",2320,20.5.1921,"Liddy Hegewalds-Film-Verleih, Leipzig","Rirefilm, Berlin",Deutschland,Spielfilm,Stummfilm,699,Jugendverbot,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_1000,R 9346-I_1000.json,NaN,NaN
4,R 9346-I/9899\nDas Flugzeug im deutschen Wirts...,NaN,14750,15.1.1927,"Otto Witte, Berlin","Otto Witte, Berlin",Deutschland,Kulturfilm,Stummfilm,564,Jugendfrei,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_10000,R 9346-I_10000.json,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36286,"R 9346-I/5301\nDeulig-Woche Nr. 20/21, 1924.\n...",NaN,8514,21.5.1924,Deulig-Film,Deulig-Film,Deutschland,Kulturfilm,Stummfilm,146,Jugendfrei,Zulassungskarte,Berlin-Lichterfelde,R_9346_I_5301,R_9346_I_5301_0001.json,NaN,NaN
36287,"R 9346-I/5473\n""Er"" sprengt die Bank.\n1920 - ...",NaN,8747,25.7.1924,"Margulies-Film GmbH, Berlin","Pathé Exchange, New York",USA,Spielfilm,Stummfilm,540,Jugendverbot,Zulassungskarte,Berlin-Lichterfelde,R_9346_I_5473,R_9346_I_5473_0001.json,NaN,NaN
36288,"R 9346-I/6196\nKurt kam, sah und siegte\n1920 ...",NaN,9701,22.1.1925,"Trianon-Film AG, Berlin","Trianon-Film AG, Berlin",Deutschland,Spielfilm,Stummfilm,740,Jugendverbot,Zulassungskarte,Berlin-Lichterfelde,R_9346_I_6196,R_9346_I_6196_0001.json,NaN,NaN
36289,"R 9346-I/7938\nliebe gute Weihnachtsmann, Der\...",NaN,12016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zulassungskarte,Berlin-Lichterfelde,R_9346_I_7938,R_9346_I_7938_0001.json,NaN,NaN
36290,R 9346-I/9116\nDer Frauen Trümpfe\n1920 - 1945,NaN,13685,13.9.1926,"Commerz-Film, Berlin","Commerz-Film, Berlin",Deutschland,Werbefilm,Stummfilm,80,Jugendfrei,Zulassungskarte,Berlin-Lichterfelde,R_9346_I_9116,R_9346_I_9116_0001.json,NaN,NaN

In [10]:
df['Prüfdatum'] = pd.to_datetime(df['Prüfdatum'], errors='coerce')

# extract year from Datetime and save in extra column
df['Jahr'] = df['Prüfdatum'].dt.year.astype('Int64')


# convert Prüfnummer to number
df['Prüfnummer'] = pd.to_numeric(df['Prüfnummer'], errors='coerce')

# sort by Prüfnummer
# df = df.sort_values(by='Prüfnummer')

In [15]:
# sample up to 10 rows safely using list comprehension
sample_df = (
    df.groupby([df["Prüfdatum"].dt.year, df["Prüfdatum"].dt.month], group_keys=False)
    .apply(lambda x: x if len(x) <= 10 else x.sample(n=10, random_state=42))
)

sample_df

,Titel_und_Signatur,Bemerkung,Prüfnummer,Prüfdatum,Antragsteller,Produktion,Land,Filmart,Stumm-/Tonfilm,Länge (in Meter),Entscheidung,Unterlagenart,Benutzungsort,_source_folder,_file_name,Vorführungsbeschränkung,Ort des Prüfdatums,Jahr
19197,R 9346-I/27293\nVon Kanada in den deutschen Wa...,NaN,44503.0,1917-01-16,"Paul Lieberenz Filmproduktion, Berlin","Paul Lieberenz Filmproduktion, Berlin",Deutschland,Kulturfilm,Stummfilm,414,Jugendfrei,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_27293,R 9346-I_27293.json,NaN,NaN,1917
19257,R 9346-I/27347\nSicher und bequem\n1920 - 1945,NaN,44585.0,1917-01-27,"Tolirag, Ton- und Lichtbildreklame AG, Berlin","Tolirag, Ton- und Lichtbildreklame AG, Berlin",Deutschland,Werbefilm,Stummfilm,47,Jugendfrei,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_27347,R 9346-I_27347.json,NaN,NaN,1917
19275,R 9346-I/27363\nVon Katzen und Grosskatzen\n19...,NaN,44615.0,1917-02-16,"Paul Lieberenz-Filmproduktion, Berlin","Paul Lieberenz-Filmproduktion, Berlin",Deutschland,Kulturfilm,Stummfilm,371,Jugendfrei,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_27363,R 9346-I_27363.json,NaN,NaN,1917
1553,R 9346-I/114\nDie Eisbärenjagd\n1920 - 1945,NaN,626.0,1920-01-01,John Hagenbeck-Film,John Hagenbeck-Film,Deutschland,Zeichentrickfilm,Stummfilm,203,Jugendfrei,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_114,R 9346-I_114.json,NaN,NaN,1920
8209,R 9346-I/174\nAfrikanisches Abenteuer\n1920 - ...,NaN,915.0,1920-01-09,"Werbefilm GmbH, Berlin","Werbefilm GmbH, Berlin",Deutschland,Kulturfilm,Stummfilm,50,Jugendfrei,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_174,R 9346-I_174.json,NaN,NaN,1920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29102,R 9346-I/36468\nDie Kellnerin Anna\n1920 - 1945,NaN,60934.0,1945-01-31,Terra Filmkunst GmbH,Terra Filmkunst GmbH,Deutschland,Spielfilm,Tonfilm,2766,Jugendfrei,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_36468,R 9346-I_36468.json,NaN,NaN,1945
29092,R 9346-I/36459\nWundervolle Märchenwelt (Der k...,NaN,60886.0,1945-01-10,"Naturfilm Hubert Schonger, Berlin","Naturfilm Hubert Schonger, Berlin",Deutschland,Spielfilm,Tonfilm,411,Jugendfrei,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_36459,R 9346-I_36459.json,NaN,NaN,1945
29096,R 9346-I/36462\nTanz mit dem Kaiser\n1920 - 1945,NaN,60892.0,1945-01-09,"Universum-Film AG, Berlin","Universum-Film AG, Berlin",Deutschland,Spielfilm,Tonfilm,2773,Jugendverbot,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_36462,R 9346-I_36462.json,NaN,NaN,1945
29100,R 9346-I/36466\nSophienlund\n1920 - 1945,NaN,60920.0,1945-02-01,Terra Filmkunst GmbH,Terra Filmkunst GmbH,Deutschland,Spielfilm,Tonfilm,2506,Jugendfrei,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_36466,R 9346-I_36466.json,NaN,NaN,1945
29101,R 9346-I/36467\nDie Stimme aus dem Äther\n1920...,NaN,60925.0,1945-02-02,Terra Filmkunst GmbH,Terra Filmkunst GmbH,Deutschland,Spielfilm,Tonfilm,2590,Jugendfrei,Zulassungskarte,Berlin-Lichterfelde,R 9346-I_36467,R 9346-I_36467.json,NaN,NaN,1945

# Copy Sample Dataset to extra folder

In [17]:
def copy_sample_folders(
    df: pd.DataFrame,
    base_dir: str = "S:/Zulassungskarten_Data",
    source_dir_name: str = "R_9346-I_Zulassungskarten",
    target_dir_name: str = "sample_dataset",
    folder_col: str = "_source_folder",
) -> None:
    source_path = Path(base_dir) / source_dir_name
    target_path = Path(base_dir) / target_dir_name

    # create target directory if not exists
    target_path.mkdir(parents=True, exist_ok=True)

    # extract unique folder names
    folder_names = df[folder_col].dropna().unique()

    for folder in folder_names:
        src = source_path / str(folder)
        dst = target_path / str(folder)

        if src.exists() and src.is_dir():
            if not dst.exists():
                shutil.copytree(src, dst)
            else:
                print(f"skipping, already exists: {dst}")
        else:
            print(f"source folder not found: {src}")

In [ ]:
copy_sample_folders(df, "S:/Zulassungskarten_Data", "R_9346-I_Zulassungskarten", "sample_dataset", "_source_folder")